version: '3.4'
services:
    
  couchbase:
    image: couchbase:community-6.0.0
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    restart: always  
    volumes:
      - ./couch:/opt/couchbase/var

  orders_service:
    image: orders-service:local
    ports:
      - "3001:3000"
    environment:
      COUCHBASE_HOST: "couchbase"
      COUCHBASE_CLUSTER_USERNAME: "Administrator"
      COUCHBASE_CLUSTER_PASSWORD: "Password01"
      COUCHBASE_ORDERS_BUCKET: "Orders"
      ALLOWED_ORIGINS: "localhost:3000"      
    depends_on:
      - couchbase
  
  products_service:
    image: products-service:local
    ports:
      - "3002:3000"
    environment:
      COUCHBASE_HOST: "couchbase"
      COUCHBASE_CLUSTER_USERNAME: "Administrator"
      COUCHBASE_CLUSTER_PASSWORD: "Password01"
      COUCHBASE_PRODUCTS_BUCKET: "Products"      
      ALLOWED_ORIGINS: "*"
    depends_on:
      - couchbase

  recommendations_service:
    image: recommendations-service:local
    ports:
      - "3003:3000"
    environment:
      COUCHBASE_HOST: "couchbase"
      COUCHBASE_CLUSTER_USERNAME: "Administrator"
      COUCHBASE_CLUSTER_PASSWORD: "Password01"
      COUCHBASE_RECOMMENDATIONS_BUCKET: "Recommendations"
      ALLOWED_ORIGINS: "localhost:3000"
    depends_on:
      - couchbase

  shopping_cart_service:
    image: shopping-cart-service:local
    ports:
      - "3004:3000"
    environment:
      COUCHBASE_HOST: "couchbase"
      COUCHBASE_CLUSTER_USERNAME: "Administrator"
      COUCHBASE_CLUSTER_PASSWORD: "Password01"
      COUCHBASE_SHOPPINGCART_BUCKET: "ShoppingCart"
      ALLOWED_ORIGINS: "localhost:3000"
    depends_on:
      - couchbase

  # frontend:
  #   image:  frontend:local
  #   ports:
  #     - "3005:80"